services:
  order_system:
    build: ./order_system
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - rabbitmq

  user_system:
    build: ./user_system
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: limon1441
      POSTGRES_DB: course_project
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
